### ISSUE TITLE
Page not found in this week's lecture notes (week 3)

### ISSUE THREAD

**Issue by mtwelker** [Watts-College/cpp-527-fall-2021#11]
On the "[Regular Expressions" page](https://watts-college.github.io/cpp-527-fall-2021/lectures/week-03/), it has a link to "Chapter" and two links to "Slides."  I can download the slides from the first link, but when I click on the second "Slides" link, I get a 404 File not found error.  
Are those two separate sets of slides, or just two ways of getting to the same set of slides?
Thanks!

**Comment by lecy** [comment]
They are two links to the same slide. One link was behaving weird (GitHub changed how it refers to branches as "main" instead of "master"). So I added a link to a previous semester. 

I must not have fixed it properly - the other link was redundant just in case.
