### ISSUE TITLE
Final project instructions?

### ISSUE THREAD

**Issue by Johaning** [Watts-College/cpp-527-fall-2021#46]
@lecy, I'm hoping to work ahead this week on the final assignments. It seems the instructions for the final project have disappeared from the course site. Can you please share the instructions?

Also the due date for the final project says Oct 8 on the course site, but Oct 5 on Canvas, so clarification on that deadline would be helpful.

Thanks!

**Comment by lecy** [comment]
It's a brand-new project, hot off the press. It took me a couple of days to build everything, but I think you will enjoy it: 

https://watts-college.github.io/cpp-527-fall-2021/labs/final-project-instructions.html

I will send a note to the class tonight with details about changes to the schedule to ensure you have time to complete everything.
