### ISSUE TITLE
Lab 06 -- Unable to submit on Canvas

### ISSUE THREAD

**Issue by mtwelker** [Watts-College/cpp-527-fall-2021#53]
When I go to Assignments in Canvas and click on Lab 06, there's no "Start Assignment" button and no way to submit my files.

**Comment by AhmedRashwanASU** [comment]
@lecy 

here too, the only way is there to add comments, I can't find any submit option for lab 6.

![image](https://user-images.githubusercontent.com/77247268/135436572-a557088e-04ca-45b2-97bd-faf420436f42.png)


![image](https://user-images.githubusercontent.com/77247268/135436348-92c76172-9b75-448a-b7c0-4df51b387226.png)

**Comment by Jana-Ajeeb** [comment]
same here

**Comment by lecy** [comment]
Sorry about that, it should be fixed. Thanks.
