### ISSUE TITLE
CSV not recognized on Mac

### ISSUE THREAD

**Issue by voznyuky** [Watts-College/cpp-527-fall-2021#58]
Professor Lecy,

I have made several attempts to edit the 'positions.csv' file but because I am working on a mac it is opening it in 'Numbers' and R cannot read it when I try to run this:

position_data <- read_csv('positions.csv') %>% 

I am not sure what my options are, if you know of a trick, please let me know. Otherwise I am just getting error codes by trying to edit excel in another program.

**Comment by voznyuky** [comment]
I think I might've figured it out. I can use 'TextEdit', a bit of a trickier process but seems to work..

**Comment by lecy** [comment]
Numbers should work, but make sure you are saving the file as a CSV when done.

You can also edit right in R:

```r
d <- read.csv( "filename.csv" )
fix( d )
```

**Comment by voznyuky** [comment]
I was looking for a code like that last night, I knew it existed, but no luck! I was able to edit in the textedit, just submitted. Thanks for the code mentioned, something I may reference later on as I will continue using the mac.
