### ISSUE TITLE
Review Sessions

### ISSUE THREAD

**Issue by millmeli42** [Watts-College/cpp-527-fall-2021#61]
Hello Professor - 

When I click on the review sessions, there are no longer options to review any of the sessions?  I was wondering if that content is just gone, or if it is a problem on my end?

Thank you,

Melissa

**Comment by lecy** [comment]
Here's a fun application of regular expression special characters. 

There is a special character in the auto-generated passcode for the zoom video this week, so it broke the markdown parser and rendered an incomplete page. 

Should be visible now!

**Comment by millmeli42** [comment]
Thank you!

Melissa
