### ISSUE TITLE
Final Project -Step 8

### ISSUE THREAD

**Issue by AhmedRashwanASU** [Watts-College/cpp-527-fall-2021#64]
Turning below into create_salary_table() function produce error , 

**invalid (NULL) left side of assignment**

t.salary <- 
  d2 %>% 
  group_by( title, gender ) %>% 
  summarize( q25=quantile(salary,0.25),
             q50=quantile(salary,0.50),
             q75=quantile(salary,0.75),
             n=n(),
             p= round( n/nrow(d), 3) ) %>% 
  ungroup()

pander( t.salary )

**Comment by lecy** [comment]
Got it working? I'm guessing you dropped the pander() call from the function?
